version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Lima/America
      - JELLYFIN_PublishedServerUrl=192.168.3.2
    volumes:
      - ${VOL_CONFIG}/jellyfin:/config
      - ${VOL_MEDIA}/series:/tv
      - ${VOL_MEDIA}/movies:/movies
    devices:
      - "/dev/dri:/dev/dri" # intel
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      # - 1900:1900/udp #optional
    restart: unless-stopped
    networks:
      - internet

networks:
  internet:
    name: internet_default
    external: true