version: "3"

services:
  autossh-80:
    image: jnovack/autossh
    container_name: autossh-80
    environment:
      - SSH_REMOTE_USER=root
      - SSH_REMOTE_HOST=${REMOTE_HOST}
      - SSH_REMOTE_PORT=22
      - SSH_TUNNEL_PORT=80
      - SSH_TARGET_HOST=nginx-proxy
      - SSH_TARGET_PORT=80
    restart: always
    volumes:
      - ${VOL_CONFIG}/autossh/autossh_id_rsa:/id_rsa
    dns:
      - 8.8.8.8
      - 1.1.1.1
  autossh-443:
    image: jnovack/autossh
    container_name: autossh-443
    environment:
      - SSH_REMOTE_USER=root
      - SSH_REMOTE_HOST=${REMOTE_HOST}
      - SSH_REMOTE_PORT=22
      - SSH_TUNNEL_PORT=443
      - SSH_TARGET_HOST=nginx-proxy
      - SSH_TARGET_PORT=443
    restart: always
    volumes:
      - ${VOL_CONFIG}/autossh/autossh_id_rsa:/id_rsa
    dns:
      - 8.8.8.8
      - 1.1.1.1
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    expose:
      - 80
      - 443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${VOL_CONFIG}/certs:/etc/nginx/certs
      - ${VOL_CONFIG}/vhost.d:/etc/nginx/vhost.d
      - ${VOL_CONFIG}/nextcloud/data:/var/www/html:ro
      - ${VOL_CONFIG}/conf.d/asset_inmutable.conf:/etc/nginx/conf.d/asset_inmutable.conf

  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    hostname: plex.${DOMAIN}
    ports:
      - 32400:32400
    expose:
      - 32400
    environment:
      PUID: 1000
      PGID: 100
      VERSION: docker
      VIRTUAL_HOST: plex.${DOMAIN}
      VIRTUAL_PORT: 32400
    volumes:
      - ${VOL_CONFIG}/plex:/config
      - ${VOL_MEDIA}/series:/tv
      - ${VOL_MEDIA}/movies:/movies
    restart: unless-stopped

  nextcloud:
    image: nextcloud:fpm
    container_name: nextcloud
    restart: unless-stopped
    hostname: nc.${DOMAIN}
    expose:
      - 9000
    volumes:
      - ${VOL_CONFIG}/nextcloud/data:/var/www/html
    environment:
      POSTGRES_HOST: nextcloud-db
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: nextcloud
      REDIS_HOST: nextcloud-redis
      NEXTCLOUD_TRUSTED_DOMAINS: nc.${DOMAIN} homeserver.local
      VIRTUAL_HOST: nc.${DOMAIN},homeserver.local
      VIRTUAL_PORT: 9000
    depends_on:
      - nextcloud-db
      - nextcloud-redis
  nextcloud-db:
    image: postgres:alpine
    container_name: nextcloud-db
    restart: always
    volumes:
      - ${VOL_CONFIG}/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: nextcloud
  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: always
  nextcloud-cron:
    image: nextcloud:fpm-alpine
    container_name: nextcloud-cron
    restart: always
    volumes:
      - ${VOL_CONFIG}/nextcloud/data:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - nextcloud-db
      - nextcloud-redis
