version: "3"

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: unless-stopped
    volumes:
      - ${VOL_CONFIG}/postgres/data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8090:8080
  redis-db:
    image: redis:7-alpine
    container_name: redis-db
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    volumes:
      - ${VOL_CONFIG}/certs:/certs
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    # ports:
    #   - 80:80
    #   - 443:443
    expose:
      - 80
      # - 443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # - ${VOL_CONFIG}/certs:/etc/nginx/certs
      - ${VOL_CONFIG}/vhost.d:/etc/nginx/vhost.d
      - ${VOL_CONFIG}/nextcloud/data:/var/www/html:ro
      - ${VOL_CONFIG}/conf.d/asset_inmutable.conf:/etc/nginx/conf.d/asset_inmutable.conf

  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    ports:
      - 32400:32400
    expose:
      - 32400
    environment:
      PUID: 1000
      PGID: 100
      VERSION: docker
      VIRTUAL_HOST: plex.${DOMAIN}
      VIRTUAL_PORT: 32400
    devices:
      - "/dev/dri:/dev/dri" # intel
    volumes:
      - ${VOL_CONFIG}/plex:/config
      - ${VOL_MEDIA}/series:/tv
      - ${VOL_MEDIA}/movies:/movies
    restart: unless-stopped

  nextcloud:
    image: nextcloud:27-fpm
    container_name: nextcloud
    restart: unless-stopped
    hostname: nc.${DOMAIN}
    volumes:
      - ${VOL_CONFIG}/nextcloud/data:/var/www/html
      - ${VOL_MEDIA}:/external/media
    environment:
      POSTGRES_HOST: postgres-db
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: nextcloud
      REDIS_HOST: redis-db
      NEXTCLOUD_TRUSTED_DOMAINS: nc.${DOMAIN} homeserver.local
      VIRTUAL_HOST: nc.${DOMAIN},homeserver.local
      VIRTUAL_PORT: 9000
    depends_on:
      - postgres-db
      - redis-db
  nextcloud-cron:
    image: nextcloud:27-fpm
    container_name: nextcloud-cron
    restart: unless-stopped
    volumes:
      - ${VOL_CONFIG}/nextcloud/data:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - postgres-db
      - redis-db
  collabora:
    image: collabora/code
    container_name: collabora
    restart: unless-stopped
    expose:
      - 9980
    environment:
      - extra_params=--o:ssl.enable=false  --o:ssl.termination=true

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    user: '1000'
    environment:
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: netdata-datasource
      PUID: 1000
      PGID: 100
      VIRTUAL_HOST: grafana.${DOMAIN}
      VIRTUAL_PORT: 3000
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ${VOL_CONFIG}/grafana:/var/lib/grafana
